"""add_audit_logs

Revision ID: bc3930636839
Revises: abb8cc2152ea
Create Date: 2026-05-21 22:38:32.873273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3930636839'
down_revision: Union[str, Sequence[str], None] = 'abb8cc2152ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicians', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_technicians_deleted_at'), 'technicians', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technicians_deleted_at'), table_name='technicians')
    op.drop_column('technicians', 'deleted_at')
    # ### end Alembic commands ###
