"""add_soft_delete_to_geofences

Revision ID: e01e7607ff49
Revises: 1edda3c32357
Create Date: 2026-05-27 00:29:19.957671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e01e7607ff49'
down_revision: Union[str, Sequence[str], None] = '1edda3c32357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('geofences', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_geofences_deleted_at'), 'geofences', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_technicians_employee_id_active'), table_name='technicians', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_technicians_employee_id'), 'technicians', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technicians_employee_id'), table_name='technicians')
    op.create_index(op.f('ix_technicians_employee_id_active'), 'technicians', ['employee_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_geofences_deleted_at'), table_name='geofences')
    op.drop_column('geofences', 'deleted_at')
    op.create_table('token_blacklist',
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('token', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=False)
    # ### end Alembic commands ###
